default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %>
  min_messages: warning
  pool: 5
  port: <%= ENV['DB_PORT_5432_TCP_PORT'] %>
  template: template0
  timeout: 5000
  username: postgres

development:
  <<: *default
  database: cardistryio_development

test:
  <<: *default
  database: cardistryio_test
